title: Mohammed Golam Kaisar Hossain Bhuyan
logo: /images/profile_pic_aug_2025.png

description: AI/ML/Data Science|Tech Lead|Digital Transformation Leader|Ex-HSBC, Ericsson, IBM, VEON, Robi Axiata, Airtel



# show_downloads: true

theme: jekyll-theme-minimal
