title: Mohammed Golam Kaisar Hossain Bhuyan
logo: /images/Profile_Picture_2.png
icons: /images/HSBC.png
icons: /images/Veon.png
icons: /images/Axiata.png
icons: /images/Ericsson.png
icons: /images/IBM.png
icons: /images/Airtel.png
# show_downloads: false
theme: jekyll-theme-minimal
